# Generated by Django 4.2.3 on 2023-07-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceania', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_oceania',
            name='carr',
            field=models.ImageField(default=1, upload_to='img/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
