# Generated by Django 4.2.3 on 2023-07-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africa', '0002_model_africa_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_africa',
            name='link',
            field=models.CharField(max_length=60),
        ),
    ]
