# Generated by Django 4.2.3 on 2023-07-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africa', '0004_comentarioaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_africa',
            name='app',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
