# Generated by Django 4.2.3 on 2023-07-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('america', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='link_url',
            field=models.CharField(default=50, max_length=100),
            preserve_default=False,
        ),
    ]
