# Generated by Django 4.2.3 on 2023-07-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('america', '0003_comentario_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='link_url',
        ),
        migrations.AddField(
            model_name='comentario',
            name='pais',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='america.model_america'),
            preserve_default=False,
        ),
    ]
