# Generated by Django 4.2.3 on 2023-07-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('america', '0006_comentario_modelo_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='modelo_pais',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='eh_publicada',
            field=models.BooleanField(default=False),
        ),
    ]
