# Generated by Django 4.2.3 on 2023-07-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('america', '0007_remove_comentario_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='link_url',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='eh_publicada',
            field=models.BooleanField(default=True),
        ),
    ]
