# Generated by Django 4.2.3 on 2023-07-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('País', 'PAÍS'), ('Continente', 'CONTINENTE')], default='', max_length=100)),
                ('eh_publicada', models.BooleanField(default=False)),
            ],
        ),
    ]
